# Generated by Django 5.1.11 on 2025-08-31 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("main", "0003_alter_data_options_data_location_idx_data_name_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="메모")),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "낮음"), (2, "보통"), (3, "높음")],
                        default=1,
                        verbose_name="우선순위",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="태그"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="추가일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarked_by",
                        to="main.data",
                        verbose_name="학원",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "즐겨찾기",
                "verbose_name_plural": "즐겨찾기 목록",
                "ordering": ["-created_at"],
                "unique_together": {("user", "academy")},
            },
        ),
        migrations.CreateModel(
            name="BookmarkFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="폴더명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "color",
                    models.CharField(
                        default="#2196F3", max_length=7, verbose_name="폴더 색상"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("folder", "📁 폴더"),
                            ("star", "⭐ 별"),
                            ("heart", "❤️ 하트"),
                            ("school", "🏫 학교"),
                            ("book", "📚 책"),
                            ("target", "🎯 타겟"),
                        ],
                        default="folder",
                        max_length=20,
                        verbose_name="아이콘",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본 폴더"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="정렬 순서")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bookmarks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="folders",
                        to="accounts.bookmark",
                        verbose_name="즐겨찾기 목록",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmark_folders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "즐겨찾기 폴더",
                "verbose_name_plural": "즐겨찾기 폴더들",
                "ordering": ["order", "name"],
                "unique_together": {("user", "name")},
            },
        ),
    ]
