# Generated by Django 5.1.11 on 2025-08-31 08:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_bookmark_bookmarkfolder"),
        ("main", "0003_alter_data_options_data_location_idx_data_name_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="종합 평점",
                    ),
                ),
                (
                    "teaching_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="강의 품질",
                    ),
                ),
                (
                    "facility_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="시설 평점",
                    ),
                ),
                (
                    "management_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="운영 관리",
                    ),
                ),
                (
                    "cost_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="비용 대비 만족도",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="리뷰 내용")),
                (
                    "attendance_period",
                    models.CharField(
                        choices=[
                            ("1개월 미만", "1개월 미만"),
                            ("1-3개월", "1-3개월"),
                            ("3-6개월", "3-6개월"),
                            ("6개월-1년", "6개월-1년"),
                            ("1년 이상", "1년 이상"),
                        ],
                        max_length=50,
                        verbose_name="수강 기간",
                    ),
                ),
                (
                    "grade_when_attended",
                    models.CharField(
                        choices=[
                            ("유아", "유아"),
                            ("초등 저학년", "초등 저학년"),
                            ("초등 고학년", "초등 고학년"),
                            ("중1", "중1"),
                            ("중2", "중2"),
                            ("중3", "중3"),
                            ("고1", "고1"),
                            ("고2", "고2"),
                            ("고3", "고3"),
                            ("재수생", "재수생"),
                            ("일반인", "일반인"),
                        ],
                        max_length=20,
                        verbose_name="수강 당시 학년",
                    ),
                ),
                (
                    "subjects_taken",
                    models.JSONField(
                        blank=True, default=list, verbose_name="수강 과목"
                    ),
                ),
                ("pros", models.TextField(blank=True, verbose_name="장점")),
                ("cons", models.TextField(blank=True, verbose_name="단점")),
                (
                    "would_recommend",
                    models.BooleanField(default=True, verbose_name="추천 여부"),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="익명 작성"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="인증된 리뷰"),
                ),
                (
                    "is_hidden",
                    models.BooleanField(default=False, verbose_name="숨김 처리"),
                ),
                (
                    "helpful_count",
                    models.PositiveIntegerField(default=0, verbose_name="도움됨 수"),
                ),
                (
                    "not_helpful_count",
                    models.PositiveIntegerField(default=0, verbose_name="도움 안됨 수"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="main.data",
                        verbose_name="학원",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "리뷰",
                "verbose_name_plural": "리뷰들",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewHelpful",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_helpful", models.BooleanField(verbose_name="도움됨 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="helpfulness_votes",
                        to="accounts.review",
                        verbose_name="리뷰",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "리뷰 유용성 평가",
                "verbose_name_plural": "리뷰 유용성 평가들",
            },
        ),
        migrations.CreateModel(
            name="ReviewImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="review_images/%Y/%m/", verbose_name="이미지"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="이미지 설명"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="accounts.review",
                        verbose_name="리뷰",
                    ),
                ),
            ],
            options={
                "verbose_name": "리뷰 이미지",
                "verbose_name_plural": "리뷰 이미지들",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("inappropriate", "부적절한 내용"),
                            ("spam", "스팸/광고"),
                            ("fake", "허위 리뷰"),
                            ("offensive", "욕설/비방"),
                            ("personal_info", "개인정보 노출"),
                            ("other", "기타"),
                        ],
                        max_length=50,
                        verbose_name="신고 사유",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="상세 설명")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("reviewing", "검토중"),
                            ("resolved", "처리완료"),
                            ("rejected", "반려"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="처리 상태",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="관리자 메모"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="신고일"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="처리일"),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="accounts.review",
                        verbose_name="신고된 리뷰",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신고자",
                    ),
                ),
            ],
            options={
                "verbose_name": "리뷰 신고",
                "verbose_name_plural": "리뷰 신고들",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["academy", "overall_rating"], name="review_academy_rating_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["created_at"], name="review_date_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["is_verified", "is_hidden"], name="review_status_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "academy")},
        ),
        migrations.AlterUniqueTogether(
            name="reviewhelpful",
            unique_together={("user", "review")},
        ),
        migrations.AlterUniqueTogether(
            name="reviewreport",
            unique_together={("user", "review")},
        ),
    ]
