# Generated by Django 5.1.11 on 2025-08-31 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_review_reviewhelpful_reviewimage_reviewreport_and_more"),
        ("main", "0003_alter_data_options_data_location_idx_data_name_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademyComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="비교 목록 이름"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "compare_tuition",
                    models.BooleanField(default=True, verbose_name="수강료 비교"),
                ),
                (
                    "compare_rating",
                    models.BooleanField(default=True, verbose_name="평점 비교"),
                ),
                (
                    "compare_distance",
                    models.BooleanField(default=True, verbose_name="거리 비교"),
                ),
                (
                    "compare_subjects",
                    models.BooleanField(default=True, verbose_name="과목 비교"),
                ),
                (
                    "compare_facilities",
                    models.BooleanField(default=True, verbose_name="시설 비교"),
                ),
                (
                    "tuition_weight",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=3,
                        verbose_name="수강료 중요도",
                    ),
                ),
                (
                    "rating_weight",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=4,
                        verbose_name="평점 중요도",
                    ),
                ),
                (
                    "distance_weight",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=3,
                        verbose_name="거리 중요도",
                    ),
                ),
                (
                    "quality_weight",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=5,
                        verbose_name="교육품질 중요도",
                    ),
                ),
                (
                    "base_latitude",
                    models.FloatField(blank=True, null=True, verbose_name="기준 위도"),
                ),
                (
                    "base_longitude",
                    models.FloatField(blank=True, null=True, verbose_name="기준 경도"),
                ),
                (
                    "base_address",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="기준 주소"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="공개 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "academies",
                    models.ManyToManyField(
                        related_name="comparisons",
                        to="main.data",
                        verbose_name="비교 대상 학원들",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "학원 비교",
                "verbose_name_plural": "학원 비교 목록",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ComparisonHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "생성"),
                            ("viewed", "조회"),
                            ("modified", "수정"),
                            ("shared", "공유"),
                            ("exported", "내보내기"),
                        ],
                        max_length=20,
                        verbose_name="작업",
                    ),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="세부사항"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comparison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="accounts.academycomparison",
                        verbose_name="비교",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparison_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "비교 기록",
                "verbose_name_plural": "비교 기록들",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComparisonTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="템플릿 이름")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("compare_tuition", models.BooleanField(default=True)),
                ("compare_rating", models.BooleanField(default=True)),
                ("compare_distance", models.BooleanField(default=True)),
                ("compare_subjects", models.BooleanField(default=True)),
                ("compare_facilities", models.BooleanField(default=True)),
                (
                    "tuition_weight",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=3,
                    ),
                ),
                (
                    "rating_weight",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=4,
                    ),
                ),
                (
                    "distance_weight",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=3,
                    ),
                ),
                (
                    "quality_weight",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=5,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본 템플릿"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparison_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "비교 템플릿",
                "verbose_name_plural": "비교 템플릿들",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="academycomparison",
            index=models.Index(
                fields=["user", "is_public"], name="comparison_user_public_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academycomparison",
            index=models.Index(fields=["created_at"], name="comparison_date_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="comparisontemplate",
            unique_together={("user", "name")},
        ),
    ]
