# Generated by Django 5.1.11 on 2025-08-31 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_academycomparison_comparisonhistory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PresetTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="테마 이름"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="표시명"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "theme_type",
                    models.CharField(
                        choices=[
                            ("light", "라이트 모드"),
                            ("dark", "다크 모드"),
                            ("auto", "시스템 자동"),
                            ("high_contrast", "고대비"),
                            ("sepia", "세피아"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "color_scheme",
                    models.CharField(
                        choices=[
                            ("default", "기본"),
                            ("blue", "블루"),
                            ("green", "그린"),
                            ("purple", "퍼플"),
                            ("orange", "오렌지"),
                            ("red", "레드"),
                            ("custom", "사용자 정의"),
                        ],
                        max_length=20,
                    ),
                ),
                ("primary_color", models.CharField(default="#2196F3", max_length=7)),
                ("secondary_color", models.CharField(default="#FF5722", max_length=7)),
                ("accent_color", models.CharField(default="#4CAF50", max_length=7)),
                (
                    "font_size",
                    models.CharField(
                        choices=[
                            ("small", "작게"),
                            ("medium", "보통"),
                            ("large", "크게"),
                            ("extra_large", "매우 크게"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="theme_previews/",
                        verbose_name="미리보기 이미지",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(default=False, verbose_name="시스템 테마"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                ("order", models.IntegerField(default=0, verbose_name="정렬 순서")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "프리셋 테마",
                "verbose_name_plural": "프리셋 테마들",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ThemeConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme_type",
                    models.CharField(
                        choices=[
                            ("light", "라이트 모드"),
                            ("dark", "다크 모드"),
                            ("auto", "시스템 자동"),
                            ("high_contrast", "고대비"),
                            ("sepia", "세피아"),
                        ],
                        default="light",
                        max_length=20,
                        verbose_name="테마 유형",
                    ),
                ),
                (
                    "color_scheme",
                    models.CharField(
                        choices=[
                            ("default", "기본"),
                            ("blue", "블루"),
                            ("green", "그린"),
                            ("purple", "퍼플"),
                            ("orange", "오렌지"),
                            ("red", "레드"),
                            ("custom", "사용자 정의"),
                        ],
                        default="default",
                        max_length=20,
                        verbose_name="색상 스키마",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#2196F3",
                        help_text="HEX 색상 코드 (#RRGGBB)",
                        max_length=7,
                        verbose_name="기본 색상",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#FF5722", max_length=7, verbose_name="보조 색상"
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#4CAF50", max_length=7, verbose_name="강조 색상"
                    ),
                ),
                (
                    "font_size",
                    models.CharField(
                        choices=[
                            ("small", "작게"),
                            ("medium", "보통"),
                            ("large", "크게"),
                            ("extra_large", "매우 크게"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="폰트 크기",
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        default="system",
                        help_text="시스템 폰트, Noto Sans KR, Roboto 등",
                        max_length=50,
                        verbose_name="폰트 패밀리",
                    ),
                ),
                (
                    "high_contrast",
                    models.BooleanField(default=False, verbose_name="고대비 모드"),
                ),
                (
                    "reduce_motion",
                    models.BooleanField(
                        default=False, verbose_name="애니메이션 줄이기"
                    ),
                ),
                (
                    "focus_indicators",
                    models.BooleanField(default=True, verbose_name="포커스 표시"),
                ),
                (
                    "sidebar_collapsed",
                    models.BooleanField(default=False, verbose_name="사이드바 접기"),
                ),
                (
                    "compact_mode",
                    models.BooleanField(default=False, verbose_name="컴팩트 모드"),
                ),
                (
                    "show_tooltips",
                    models.BooleanField(default=True, verbose_name="툴팁 표시"),
                ),
                (
                    "map_style",
                    models.CharField(
                        choices=[
                            ("default", "기본"),
                            ("satellite", "위성"),
                            ("terrain", "지형"),
                            ("hybrid", "하이브리드"),
                        ],
                        default="default",
                        max_length=20,
                        verbose_name="지도 스타일",
                    ),
                ),
                (
                    "auto_dark_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="다크모드 시작 시간"
                    ),
                ),
                (
                    "auto_dark_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="다크모드 종료 시간"
                    ),
                ),
                (
                    "custom_css",
                    models.TextField(
                        blank=True,
                        help_text="고급 사용자용 커스텀 스타일",
                        verbose_name="사용자 정의 CSS",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_config",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "테마 설정",
                "verbose_name_plural": "테마 설정들",
            },
        ),
        migrations.CreateModel(
            name="ThemeUsageStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme_name",
                    models.CharField(max_length=50, verbose_name="테마 이름"),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="사용 횟수"),
                ),
                (
                    "active_users",
                    models.IntegerField(default=0, verbose_name="활성 사용자 수"),
                ),
                (
                    "stats_date",
                    models.DateField(auto_now_add=True, verbose_name="통계 날짜"),
                ),
            ],
            options={
                "verbose_name": "테마 사용 통계",
                "verbose_name_plural": "테마 사용 통계들",
                "ordering": ["-stats_date", "-usage_count"],
                "unique_together": {("theme_name", "stats_date")},
            },
        ),
        migrations.CreateModel(
            name="UserThemeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme_name",
                    models.CharField(max_length=50, verbose_name="테마 이름"),
                ),
                ("theme_settings", models.JSONField(verbose_name="테마 설정")),
                (
                    "applied_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="적용 시간"),
                ),
                (
                    "application_method",
                    models.CharField(
                        choices=[
                            ("manual", "수동 선택"),
                            ("auto", "자동 전환"),
                            ("preset", "프리셋 적용"),
                            ("import", "설정 가져오기"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="적용 방식",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "테마 변경 이력",
                "verbose_name_plural": "테마 변경 이력들",
                "ordering": ["-applied_at"],
            },
        ),
    ]
