# Generated by Django 5.1.11 on 2025-08-31 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_presettheme_themeconfiguration_themeusagestatistics_and_more",
        ),
        ("main", "0003_alter_data_options_data_location_idx_data_name_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="플랫폼명"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="표시명"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="아이콘"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#000000", max_length=7, verbose_name="브랜드 색상"
                    ),
                ),
                (
                    "share_url_template",
                    models.URLField(
                        help_text="변수: {url}, {title}, {description}, {hashtags}",
                        max_length=500,
                        verbose_name="공유 URL 템플릿",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                ("order", models.IntegerField(default=0, verbose_name="정렬 순서")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "소셜 플랫폼",
                "verbose_name_plural": "소셜 플랫폼들",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ShareableContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("academy", "학원 정보"),
                            ("comparison", "학원 비교"),
                            ("review", "리뷰"),
                            ("list", "학원 목록"),
                            ("search_result", "검색 결과"),
                        ],
                        max_length=20,
                        verbose_name="콘텐츠 유형",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                ("url", models.URLField(verbose_name="대상 URL")),
                ("image_url", models.URLField(blank=True, verbose_name="이미지 URL")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="메타데이터"
                    ),
                ),
                (
                    "hashtags",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="해시태그"
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="OG 제목"
                    ),
                ),
                (
                    "og_description",
                    models.TextField(blank=True, verbose_name="OG 설명"),
                ),
                ("og_image", models.URLField(blank=True, verbose_name="OG 이미지")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "공유 콘텐츠",
                "verbose_name_plural": "공유 콘텐츠들",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PopularContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_shares",
                    models.IntegerField(default=0, verbose_name="총 공유 수"),
                ),
                (
                    "weekly_shares",
                    models.IntegerField(default=0, verbose_name="주간 공유 수"),
                ),
                (
                    "monthly_shares",
                    models.IntegerField(default=0, verbose_name="월간 공유 수"),
                ),
                (
                    "average_engagement",
                    models.FloatField(default=0.0, verbose_name="평균 참여도"),
                ),
                (
                    "viral_score",
                    models.FloatField(default=0.0, verbose_name="바이럴 점수"),
                ),
                (
                    "last_calculated",
                    models.DateTimeField(auto_now=True, verbose_name="마지막 계산"),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.shareablecontent",
                        verbose_name="콘텐츠",
                    ),
                ),
            ],
            options={
                "verbose_name": "인기 콘텐츠",
                "verbose_name_plural": "인기 콘텐츠들",
                "ordering": ["-viral_score", "-total_shares"],
            },
        ),
        migrations.CreateModel(
            name="AcademyShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="사용자 정의 제목"
                    ),
                ),
                (
                    "custom_description",
                    models.TextField(blank=True, verbose_name="사용자 정의 설명"),
                ),
                (
                    "selected_subjects",
                    models.JSONField(
                        blank=True, default=list, verbose_name="선택된 과목"
                    ),
                ),
                (
                    "include_rating",
                    models.BooleanField(default=True, verbose_name="평점 포함"),
                ),
                (
                    "include_price",
                    models.BooleanField(default=False, verbose_name="가격 포함"),
                ),
                (
                    "include_location",
                    models.BooleanField(default=True, verbose_name="위치 포함"),
                ),
                (
                    "recommendation_reason",
                    models.TextField(blank=True, verbose_name="추천 이유"),
                ),
                (
                    "target_age_group",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="대상 연령대"
                    ),
                ),
                ("shared_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="main.data",
                        verbose_name="공유된 학원",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academy_shares",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="공유한 사용자",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.socialplatform",
                        verbose_name="플랫폼",
                    ),
                ),
            ],
            options={
                "verbose_name": "학원 공유",
                "verbose_name_plural": "학원 공유들",
                "ordering": ["-shared_at"],
            },
        ),
        migrations.CreateModel(
            name="ShareAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="날짜")),
                (
                    "total_shares",
                    models.IntegerField(default=0, verbose_name="총 공유 수"),
                ),
                (
                    "unique_users",
                    models.IntegerField(default=0, verbose_name="순 사용자 수"),
                ),
                (
                    "total_clicks",
                    models.IntegerField(default=0, verbose_name="총 클릭 수"),
                ),
                (
                    "academy_shares",
                    models.IntegerField(default=0, verbose_name="학원 공유 수"),
                ),
                (
                    "comparison_shares",
                    models.IntegerField(default=0, verbose_name="비교 공유 수"),
                ),
                (
                    "review_shares",
                    models.IntegerField(default=0, verbose_name="리뷰 공유 수"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.socialplatform",
                        verbose_name="플랫폼",
                    ),
                ),
            ],
            options={
                "verbose_name": "공유 분석",
                "verbose_name_plural": "공유 분석 데이터",
                "ordering": ["-date", "platform"],
                "unique_together": {("date", "platform")},
            },
        ),
        migrations.CreateModel(
            name="SocialShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shared_url", models.URLField(verbose_name="실제 공유된 URL")),
                (
                    "custom_message",
                    models.TextField(blank=True, verbose_name="사용자 메시지"),
                ),
                ("clicks", models.IntegerField(default=0, verbose_name="클릭 수")),
                (
                    "engagement_score",
                    models.FloatField(default=0.0, verbose_name="참여도 점수"),
                ),
                (
                    "shared_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="공유 시간"),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.shareablecontent",
                        verbose_name="공유 콘텐츠",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.socialplatform",
                        verbose_name="플랫폼",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_shares",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "소셜 공유",
                "verbose_name_plural": "소셜 공유 기록",
                "ordering": ["-shared_at"],
                "unique_together": {("user", "platform", "content", "shared_at")},
            },
        ),
    ]
