# Generated by Django 5.2.5 on 2025-08-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_data_학원사진"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="data",
            options={"verbose_name": "학원", "verbose_name_plural": "학원들"},
        ),
        migrations.AddIndex(
            model_name="data",
            index=models.Index(fields=["경도", "위도"], name="location_idx"),
        ),
        migrations.AddIndex(
            model_name="data",
            index=models.Index(fields=["상호명"], name="name_idx"),
        ),
        migrations.AddIndex(
            model_name="data",
            index=models.Index(fields=["시도명", "시군구명"], name="region_idx"),
        ),
        migrations.AddIndex(
            model_name="data",
            index=models.Index(fields=["별점"], name="rating_idx"),
        ),
        migrations.AddIndex(
            model_name="data",
            index=models.Index(fields=["과목_수학"], name="subject_math_idx"),
        ),
        migrations.AddIndex(
            model_name="data",
            index=models.Index(fields=["과목_영어"], name="subject_eng_idx"),
        ),
        migrations.AddIndex(
            model_name="data",
            index=models.Index(fields=["과목_종합"], name="subject_general_idx"),
        ),
    ]
