# Generated by Django 5.1.11 on 2025-08-31 08:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_data_options_data_location_idx_data_name_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademyComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comparison_data",
                    models.JSONField(default=dict, verbose_name="비교 데이터"),
                ),
                ("strengths", models.JSONField(default=list, verbose_name="강점")),
                ("weaknesses", models.JSONField(default=list, verbose_name="개선점")),
                (
                    "competitor_count",
                    models.IntegerField(default=0, verbose_name="경쟁 학원 수"),
                ),
                (
                    "price_competitiveness",
                    models.FloatField(default=0.0, verbose_name="가격 경쟁력"),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons",
                        to="main.data",
                        verbose_name="학원",
                    ),
                ),
            ],
            options={
                "verbose_name": "학원 비교",
                "verbose_name_plural": "학원 비교들",
            },
        ),
        migrations.CreateModel(
            name="AcademyDetailInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facilities",
                    models.JSONField(
                        blank=True, default=list, verbose_name="시설 정보"
                    ),
                ),
                (
                    "total_classrooms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="총 강의실 수"
                    ),
                ),
                (
                    "max_students_per_class",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="반별 최대 학생 수"
                    ),
                ),
                (
                    "total_teachers",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="총 강사 수"
                    ),
                ),
                (
                    "teacher_student_ratio",
                    models.FloatField(
                        blank=True, null=True, verbose_name="강사:학생 비율"
                    ),
                ),
                (
                    "established_year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2025),
                        ],
                        verbose_name="설립년도",
                    ),
                ),
                ("website_url", models.URLField(blank=True, verbose_name="홈페이지")),
                (
                    "social_media",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="소셜미디어"
                    ),
                ),
                (
                    "programs",
                    models.JSONField(
                        blank=True, default=list, verbose_name="교육 프로그램"
                    ),
                ),
                (
                    "special_programs",
                    models.TextField(blank=True, verbose_name="특별 프로그램"),
                ),
                (
                    "class_schedule",
                    models.JSONField(blank=True, default=dict, verbose_name="시간표"),
                ),
                (
                    "registration_fee",
                    models.IntegerField(blank=True, null=True, verbose_name="등록비"),
                ),
                (
                    "material_fee",
                    models.IntegerField(blank=True, null=True, verbose_name="교재비"),
                ),
                (
                    "has_scholarship",
                    models.BooleanField(default=False, verbose_name="장학금 제도"),
                ),
                (
                    "parking_info",
                    models.TextField(blank=True, verbose_name="주차 정보"),
                ),
                (
                    "transportation_info",
                    models.TextField(blank=True, verbose_name="교통 정보"),
                ),
                ("notice", models.TextField(blank=True, verbose_name="공지사항")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail_info",
                        to="main.data",
                        verbose_name="학원",
                    ),
                ),
            ],
            options={
                "verbose_name": "학원 상세정보",
                "verbose_name_plural": "학원 상세정보들",
            },
        ),
        migrations.CreateModel(
            name="AcademyFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200, verbose_name="질문")),
                ("answer", models.TextField(verbose_name="답변")),
                ("order", models.IntegerField(default=0, verbose_name="순서")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="main.data",
                        verbose_name="학원",
                    ),
                ),
            ],
            options={
                "verbose_name": "자주 묻는 질문",
                "verbose_name_plural": "자주 묻는 질문들",
                "ordering": ["academy", "order"],
            },
        ),
        migrations.CreateModel(
            name="AcademyGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(max_length=500, verbose_name="이미지 URL"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("exterior", "외관"),
                            ("interior", "내부"),
                            ("classroom", "강의실"),
                            ("facility", "시설"),
                            ("activity", "활동사진"),
                            ("certificate", "인증서"),
                            ("event", "행사"),
                        ],
                        default="interior",
                        max_length=20,
                        verbose_name="카테고리",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=100, verbose_name="제목"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("order", models.IntegerField(default=0, verbose_name="정렬순서")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="main.data",
                        verbose_name="학원",
                    ),
                ),
            ],
            options={
                "verbose_name": "학원 갤러리",
                "verbose_name_plural": "학원 갤러리들",
                "ordering": ["academy", "category", "order"],
            },
        ),
        migrations.CreateModel(
            name="AcademyNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "news_type",
                    models.CharField(
                        choices=[
                            ("notice", "공지사항"),
                            ("event", "이벤트"),
                            ("news", "소식"),
                            ("achievement", "수상/성과"),
                        ],
                        default="notice",
                        max_length=20,
                        verbose_name="유형",
                    ),
                ),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="중요"),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="상단고정"),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="게시일"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="종료일"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to="main.data",
                        verbose_name="학원",
                    ),
                ),
            ],
            options={
                "verbose_name": "학원 소식",
                "verbose_name_plural": "학원 소식들",
                "ordering": ["-is_pinned", "-is_important", "-publish_date"],
            },
        ),
        migrations.CreateModel(
            name="AcademyStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="조회수")),
                (
                    "monthly_views",
                    models.IntegerField(default=0, verbose_name="월간 조회수"),
                ),
                (
                    "bookmark_count",
                    models.IntegerField(default=0, verbose_name="즐겨찾기 수"),
                ),
                ("share_count", models.IntegerField(default=0, verbose_name="공유 수")),
                (
                    "review_count",
                    models.IntegerField(default=0, verbose_name="리뷰 수"),
                ),
                (
                    "average_rating",
                    models.FloatField(default=0.0, verbose_name="평균 평점"),
                ),
                (
                    "local_rank",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="지역 순위"
                    ),
                ),
                (
                    "category_rank",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="카테고리 순위"
                    ),
                ),
                (
                    "popularity_score",
                    models.FloatField(default=0.0, verbose_name="인기도 점수"),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="main.data",
                        verbose_name="학원",
                    ),
                ),
            ],
            options={
                "verbose_name": "학원 통계",
                "verbose_name_plural": "학원 통계들",
            },
        ),
        migrations.CreateModel(
            name="AcademyViewHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                ("session_id", models.CharField(blank=True, max_length=40)),
                ("referrer", models.URLField(blank=True)),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="체류시간(초)"
                    ),
                ),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_history",
                        to="main.data",
                        verbose_name="학원",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "조회 기록",
                "verbose_name_plural": "조회 기록들",
                "ordering": ["-viewed_at"],
            },
        ),
    ]
