# Generated by Django 5.1.11 on 2025-08-31 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_academycomparison_academydetailinfo_academyfaq_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academycomparison",
            name="academy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_comparisons",
                to="main.data",
                verbose_name="학원",
            ),
        ),
    ]
