# Generated by Django 5.1.11 on 2025-08-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_academycomparison_academy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academyviewhistory",
            name="session_id",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
