# Generated by Django 5.1.11 on 2025-08-31 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_academyinquiry_academyowner_academypromotion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversionFunnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="날짜")),
                (
                    "stage_1_visitors",
                    models.IntegerField(default=0, verbose_name="1단계: 방문자"),
                ),
                (
                    "stage_2_search",
                    models.IntegerField(default=0, verbose_name="2단계: 검색"),
                ),
                (
                    "stage_3_view",
                    models.IntegerField(default=0, verbose_name="3단계: 학원 조회"),
                ),
                (
                    "stage_4_detail",
                    models.IntegerField(default=0, verbose_name="4단계: 상세 조회"),
                ),
                (
                    "stage_5_inquiry",
                    models.IntegerField(default=0, verbose_name="5단계: 문의"),
                ),
                (
                    "search_conversion",
                    models.FloatField(default=0.0, verbose_name="검색 전환율(%)"),
                ),
                (
                    "view_conversion",
                    models.FloatField(default=0.0, verbose_name="조회 전환율(%)"),
                ),
                (
                    "detail_conversion",
                    models.FloatField(default=0.0, verbose_name="상세 전환율(%)"),
                ),
                (
                    "inquiry_conversion",
                    models.FloatField(default=0.0, verbose_name="문의 전환율(%)"),
                ),
                (
                    "stage_1_drop",
                    models.FloatField(default=0.0, verbose_name="1단계 이탈률(%)"),
                ),
                (
                    "stage_2_drop",
                    models.FloatField(default=0.0, verbose_name="2단계 이탈률(%)"),
                ),
                (
                    "stage_3_drop",
                    models.FloatField(default=0.0, verbose_name="3단계 이탈률(%)"),
                ),
                (
                    "stage_4_drop",
                    models.FloatField(default=0.0, verbose_name="4단계 이탈률(%)"),
                ),
                (
                    "overall_conversion",
                    models.FloatField(default=0.0, verbose_name="전체 전환율(%)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "전환 퍼널",
                "verbose_name_plural": "전환 퍼널들",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date"], name="main_conver_date_e25f9e_idx")
                ],
                "unique_together": {("date",)},
            },
        ),
        migrations.CreateModel(
            name="MarketTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trend_type",
                    models.CharField(
                        choices=[
                            ("subject_popularity", "과목별 인기도"),
                            ("price_trend", "수강료 트렌드"),
                            ("regional_growth", "지역별 성장률"),
                            ("user_preference", "사용자 선호도"),
                            ("seasonal_trend", "계절별 트렌드"),
                        ],
                        max_length=30,
                        verbose_name="트렌드 유형",
                    ),
                ),
                ("date", models.DateField(verbose_name="날짜")),
                (
                    "trend_data",
                    models.JSONField(default=dict, verbose_name="트렌드 데이터"),
                ),
                (
                    "trend_score",
                    models.FloatField(default=0.0, verbose_name="트렌드 점수"),
                ),
                (
                    "change_rate",
                    models.FloatField(default=0.0, verbose_name="변화율(%)"),
                ),
                (
                    "change_direction",
                    models.CharField(
                        choices=[("up", "상승"), ("down", "하락"), ("stable", "안정")],
                        default="stable",
                        max_length=20,
                        verbose_name="변화 방향",
                    ),
                ),
                (
                    "prediction_data",
                    models.JSONField(default=dict, verbose_name="예측 데이터"),
                ),
                (
                    "confidence_level",
                    models.FloatField(default=0.0, verbose_name="신뢰도"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="트렌드 설명"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "시장 트렌드",
                "verbose_name_plural": "시장 트렌드들",
                "ordering": ["-date", "trend_type"],
                "indexes": [
                    models.Index(
                        fields=["trend_type", "date"],
                        name="main_market_trend_t_b77203_idx",
                    ),
                    models.Index(
                        fields=["date", "trend_score"],
                        name="main_market_date_33f8cc_idx",
                    ),
                ],
                "unique_together": {("trend_type", "date")},
            },
        ),
        migrations.CreateModel(
            name="RegionalAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region_sido", models.CharField(max_length=50, verbose_name="시도")),
                (
                    "region_sigungu",
                    models.CharField(max_length=50, verbose_name="시군구"),
                ),
                ("date", models.DateField(verbose_name="날짜")),
                (
                    "total_academies",
                    models.IntegerField(default=0, verbose_name="총 학원 수"),
                ),
                (
                    "active_academies",
                    models.IntegerField(default=0, verbose_name="활성 학원 수"),
                ),
                (
                    "total_views",
                    models.IntegerField(default=0, verbose_name="총 조회수"),
                ),
                (
                    "unique_visitors",
                    models.IntegerField(default=0, verbose_name="순 방문자 수"),
                ),
                (
                    "avg_rating",
                    models.FloatField(default=0.0, verbose_name="평균 평점"),
                ),
                (
                    "avg_tuition",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="평균 수강료",
                    ),
                ),
                (
                    "tuition_range_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="최저 수강료",
                    ),
                ),
                (
                    "tuition_range_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="최고 수강료",
                    ),
                ),
                (
                    "subject_distribution",
                    models.JSONField(default=dict, verbose_name="과목별 분포"),
                ),
                (
                    "competition_index",
                    models.FloatField(default=0.0, verbose_name="경쟁 지수"),
                ),
                (
                    "market_saturation",
                    models.FloatField(default=0.0, verbose_name="시장 포화도"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "지역 분석",
                "verbose_name_plural": "지역 분석들",
                "ordering": ["-date", "region_sido", "region_sigungu"],
                "indexes": [
                    models.Index(
                        fields=["region_sido", "region_sigungu"],
                        name="main_region_region__5f0808_idx",
                    ),
                    models.Index(fields=["date"], name="main_region_date_153272_idx"),
                ],
                "unique_together": {("region_sido", "region_sigungu", "date")},
            },
        ),
        migrations.CreateModel(
            name="UserAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="날짜")),
                (
                    "total_users",
                    models.IntegerField(default=0, verbose_name="총 사용자 수"),
                ),
                (
                    "new_users",
                    models.IntegerField(default=0, verbose_name="신규 사용자 수"),
                ),
                (
                    "returning_users",
                    models.IntegerField(default=0, verbose_name="재방문 사용자 수"),
                ),
                (
                    "total_sessions",
                    models.IntegerField(default=0, verbose_name="총 세션 수"),
                ),
                (
                    "avg_session_duration",
                    models.FloatField(default=0.0, verbose_name="평균 세션 시간(초)"),
                ),
                (
                    "bounce_rate",
                    models.FloatField(default=0.0, verbose_name="이탈률(%)"),
                ),
                (
                    "total_pageviews",
                    models.IntegerField(default=0, verbose_name="총 페이지 뷰"),
                ),
                (
                    "unique_pageviews",
                    models.IntegerField(default=0, verbose_name="순 페이지 뷰"),
                ),
                (
                    "avg_pages_per_session",
                    models.FloatField(default=0.0, verbose_name="세션당 페이지 수"),
                ),
                (
                    "organic_traffic",
                    models.IntegerField(default=0, verbose_name="자연 검색 트래픽"),
                ),
                (
                    "direct_traffic",
                    models.IntegerField(default=0, verbose_name="직접 방문 트래픽"),
                ),
                (
                    "referral_traffic",
                    models.IntegerField(default=0, verbose_name="추천 사이트 트래픽"),
                ),
                (
                    "social_traffic",
                    models.IntegerField(default=0, verbose_name="소셜 미디어 트래픽"),
                ),
                (
                    "desktop_users",
                    models.IntegerField(default=0, verbose_name="데스크톱 사용자"),
                ),
                (
                    "mobile_users",
                    models.IntegerField(default=0, verbose_name="모바일 사용자"),
                ),
                (
                    "tablet_users",
                    models.IntegerField(default=0, verbose_name="태블릿 사용자"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "사용자 분석",
                "verbose_name_plural": "사용자 분석들",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date"], name="main_useran_date_c28aa4_idx")
                ],
                "unique_together": {("date",)},
            },
        ),
        migrations.CreateModel(
            name="AcademyAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="날짜")),
                ("views", models.IntegerField(default=0, verbose_name="조회수")),
                (
                    "unique_views",
                    models.IntegerField(default=0, verbose_name="순 조회수"),
                ),
                (
                    "avg_view_duration",
                    models.FloatField(default=0.0, verbose_name="평균 조회 시간(초)"),
                ),
                ("bookmarks", models.IntegerField(default=0, verbose_name="북마크 수")),
                ("shares", models.IntegerField(default=0, verbose_name="공유 수")),
                ("inquiries", models.IntegerField(default=0, verbose_name="문의 수")),
                (
                    "conversion_rate",
                    models.FloatField(default=0.0, verbose_name="전환율(%)"),
                ),
                (
                    "inquiry_conversion",
                    models.FloatField(default=0.0, verbose_name="문의 전환율(%)"),
                ),
                (
                    "top_keywords",
                    models.JSONField(default=list, verbose_name="상위 검색 키워드"),
                ),
                (
                    "recommendation_score",
                    models.FloatField(default=0.0, verbose_name="추천 점수"),
                ),
                (
                    "popularity_rank",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="인기 순위"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_data",
                        to="main.data",
                        verbose_name="학원",
                    ),
                ),
            ],
            options={
                "verbose_name": "학원 분석",
                "verbose_name_plural": "학원 분석들",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["academy", "date"],
                        name="main_academ_academy_75db0e_idx",
                    ),
                    models.Index(
                        fields=["date", "views"], name="main_academ_date_17ad98_idx"
                    ),
                ],
                "unique_together": {("academy", "date")},
            },
        ),
        migrations.CreateModel(
            name="AnalyticsReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="리포트 제목")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "일일 리포트"),
                            ("weekly", "주간 리포트"),
                            ("monthly", "월간 리포트"),
                            ("quarterly", "분기 리포트"),
                            ("yearly", "연간 리포트"),
                            ("custom", "사용자 정의"),
                        ],
                        max_length=20,
                        verbose_name="리포트 유형",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("traffic", "트래픽 분석"),
                            ("user_behavior", "사용자 행동"),
                            ("academy_performance", "학원 성과"),
                            ("regional_analysis", "지역 분석"),
                            ("market_trends", "시장 트렌드"),
                            ("conversion", "전환 분석"),
                        ],
                        max_length=30,
                        verbose_name="분석 카테고리",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("end_date", models.DateField(verbose_name="종료일")),
                ("data", models.JSONField(default=dict, verbose_name="분석 데이터")),
                ("summary", models.TextField(verbose_name="요약")),
                ("insights", models.JSONField(default=list, verbose_name="인사이트")),
                (
                    "recommendations",
                    models.JSONField(default=list, verbose_name="추천사항"),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="공개 여부"),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "분석 리포트",
                "verbose_name_plural": "분석 리포트들",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["report_type", "category"],
                        name="main_analyt_report__0b0297_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="main_analyt_start_d_2f4650_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="대시보드 이름"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "layout_config",
                    models.JSONField(default=dict, verbose_name="레이아웃 설정"),
                ),
                (
                    "widget_config",
                    models.JSONField(default=list, verbose_name="위젯 설정"),
                ),
                (
                    "filter_config",
                    models.JSONField(default=dict, verbose_name="필터 설정"),
                ),
                (
                    "is_shared",
                    models.BooleanField(default=False, verbose_name="공유 여부"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본 대시보드"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_dashboards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="공유 대상",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_dashboards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 정의 대시보드",
                "verbose_name_plural": "사용자 정의 대시보드들",
                "ordering": ["user", "-is_default", "name"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_default"],
                        name="main_custom_user_id_c0cccb_idx",
                    )
                ],
            },
        ),
    ]
