# Generated by Django 4.2.19 on 2025-05-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Academy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "상가업소번호",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("상호명", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "상권업종대분류코드",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "상권업종대분류명",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "상권업종중분류명",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "상권업종소분류명",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("시도명", models.CharField(blank=True, max_length=255, null=True)),
                ("시군구명", models.CharField(blank=True, max_length=255, null=True)),
                ("행정동명", models.CharField(blank=True, max_length=255, null=True)),
                ("법정동명", models.CharField(blank=True, max_length=255, null=True)),
                ("지번주소", models.CharField(blank=True, max_length=255, null=True)),
                ("도로명주소", models.CharField(blank=True, max_length=255, null=True)),
                ("경도", models.FloatField(blank=True, null=True)),
                ("위도", models.FloatField(blank=True, null=True)),
                ("학원사진", models.URLField(blank=True, max_length=500, null=True)),
                ("대표원장", models.CharField(blank=True, max_length=255, null=True)),
                ("레벨테스트", models.CharField(blank=True, max_length=255, null=True)),
                ("강사", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "대상_유아",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "대상_초등",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "대상_중등",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "대상_고등",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "대상_특목고",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "대상_일반",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "대상_기타",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "인증_명문대",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "인증_경력",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("소개글", models.TextField(blank=True, null=True)),
                (
                    "과목_종합",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "과목_수학",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "과목_영어",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "과목_과학",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "과목_외국어",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "과목_예체능",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "과목_컴퓨터",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "과목_논술",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "과목_기타",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "과목_독서실스터디카페",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "별점",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("전화번호", models.CharField(blank=True, max_length=255, null=True)),
                ("영업시간", models.CharField(blank=True, max_length=255, null=True)),
                ("셔틀버스", models.CharField(blank=True, max_length=255, null=True)),
                ("수강료", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "수강료_평균",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
